.\"
.\" AGRESS - прогрессивный аудио кодер
.\" Copyleft (C) 2004 Александр Симаков
.\"
.\" http://www.entropyware.info
.\" xander@entropyware.info
.\"
.TH "AGPLAY" "1" "Декабрь 2004" "AGPLAY(1)" "AGRESS - прогрессивный аудио кодер"
.SH "ИМЯ"
.LP
agplay \- аудиоплеер файлов формата agress
.SH "СИНТАКСИС"
.LP
agplay [\fBФАЙЛЫ...\fR]
.SH "ОПИСАНИЕ"
.LP
Данная программа позволяет воспроизводить файлы, закодированные
при помощи \fBagcodec\fR.
.SH "ПРИМЕРЫ"
.LP
agplay *.agress
.SH "АВТОР"
.LP
Александр Симаков <xander@entropyware.info>
.SH "СМОТРИ ТАКЖЕ"
.LP
agcodec(1).
