.\"
.\" AGRESS - progressive audio coder
.\" Copyleft (C) 2004 Alexander Simakov
.\"
.\" http://www.entropyware.info
.\" xander@entropyware.info
.\"
.TH "AGPLAY" "1" "14 Jul 2019" "AGPLAY(1)" "User Manual"

.SH NAME
.LP
agplay \- player files format agress

.SH SYNOPSIS
.LP
agplay [\fBfiles...\fR]

.SH DESCRIPTION
.LP
This program allows you to play files encoded with \fBagcodec\fR.

.SH EXAMPLE
.LP
agplay *.agress

.SH AUTHORS
.LP
АAlexander Simakov <xander@entropyware.info>

.SH SEE ALSO
.LP
agcodec(1).
